### PR TITLE
invoke /usr/bin/reboot for both init systems

### PR DESCRIPTION
**Pull request by oberon2007**
`/usr/bin/reboot` is present in both init systems. So this should work I think.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Well, I'll use some differnt as it might not be present on all systems:
```
[phil@manjaro ~]$ pacman -Qo /usr/bin/reboot
/usr/bin/reboot ist in systemd-sysvcompat 224-1 enthalten
```

**Comment by oberon2007** [comment]
`pacman -Qo /usr/bin/reboot
/usr/bin/reboot is owned by sysvinit 2.88-16` :)

**Comment by philmmanjaro** [comment]
Well, **thus 0.9.0** already has a fix for it.

**Comment by philmmanjaro** [comment]
Well, **thus 0.9.0** already has a fix for it.

**Pull request closed without merging**
