### PR TITLE
process.py: add check and repo_path

### PR DESCRIPTION
**Pull request by udeved**
Please review, I am no hero with python.

### CODE REVIEW

**Comment by udeved** [comment]
https://github.com/manjaro/thus/pull/46/files

like this?

**Comment by Kirek** [comment]
yes, this looks good

**Comment by udeved** [comment]
Do you merge? Should i do?

**Comment by udeved** [comment]
Out of curiosity.
self.foo is only for class member calls?
self=this,->?

**Comment by Kirek** [comment]
Yes, something like that.

**Pull request merged**
